encryptionsalt: v1:QhwfcI/hljA=:v1:p+DK2nNNcd4oZUjI:ZzbVH1xnyC46XpQPci22MNrPNg+Z8A==
config:
  nftcom:tsAutoScaleMin: "3"
  nftcom:tsAvailabilityZones: us-east-1a,us-east-1b,us-east-1c
  nftcom:tsEbsSize: "50"
  nftcom:tsInstance: r6a.2xlarge