name: Deploy Env
description: Deploys the infrastrcuture and apps to an environment
inputs:
  stage:
    description: Environment to deploy on
    required: true
    default: dev
  secrets:
    description: Secrets
    required: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ fromJSON(inputs.secrets).AWS_ACCESS_KEY_ID }}
        aws-region: ${{ fromJSON(inputs.secrets).AWS_REGION }}
        aws-secret-access-key: ${{ fromJSON(inputs.secrets).AWS_SECRET_ACCESS_KEY }}
    - name: Install pulumi
      uses: pulumi/setup-pulumi@v2
    - name: Login to Pulumi backend
      shell: bash
      run: pulumi login s3://nftcom-pulumi-state
    - name: Install Infra Deps
      working-directory: infra
      shell: bash
      env:
        GH_TOKEN: ${{ fromJSON(inputs.secrets).GH_TOKEN }}
      run: |
        git config --global url."https://${GH_TOKEN}@github.com".insteadOf ssh://git@github.com
        npm install
    - name: Deploy Shared Infra
      working-directory: infra
      shell: bash
      env:
        STAGE: ${{ inputs.stage }}
        PULUMI_CONFIG_PASSPHRASE: ""
        AWS_ACCOUNT_ID: ${{ fromJSON(inputs.secrets).AWS_ACCOUNT_ID }}
        DB_PASSWORD: ${{ fromJSON(inputs.secrets).DB_PASSWORD }}
      run: npm run deploy:shared
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          typesense:
            - 'infra/typesense/**'
    - name: Deploy Typesense Infra
      if: ${{ steps.filter.outputs.typesense == 'true' }}
      shell: bash
      working-directory: infra
      env:
        STAGE: ${{ inputs.stage }}
        PULUMI_CONFIG_PASSPHRASE: ""
        AWS_ACCOUNT_ID: ${{ fromJSON(inputs.secrets).AWS_ACCOUNT_ID }}
      run: npm run deploy:typesense
