name: NFT.com github actions
on: [push]
jobs:
  deploy-dev:
    if: ${{ startsWith(github.ref_name, 'feat') || startsWith(github.ref_name, 'fix') }}
    runs-on: ubuntu-latest
    environment: nftcom_search_dev
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets. CROSSREPO_PAT}}
      - uses: ./.github/actions/deploy-env
        name: Deploy env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: dev
  deploy-staging:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    environment: nftcom_search_staging
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets. CROSSREPO_PAT}}
      - uses: ./.github/actions/deploy-env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: staging
  deploy-prod:
    if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'rel') }}
    runs-on: ubuntu-latest
    environment: nftcom_search_prod
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets. CROSSREPO_PAT}}
      - uses: ./.github/actions/deploy-env
        with:
          secrets: ${{ toJSON(secrets) }}
          stage: prod
